<x-app-layout>
    <x-slot name="header"><div><a href="{{ route('portal.car-hire-bookings.index') }}" class="text-sm font-bold text-emerald-800 underline">Back to my hire requests</a><div class="mt-4 flex flex-wrap items-center gap-2"><p class="font-mono text-xs font-bold text-emerald-700">{{ $booking->reference }}</p><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{{ $booking->status->label() }}</span></div><h1 class="mt-2 text-2xl font-bold text-slate-950">{{ $booking->vehicle_name_snapshot }}</h1></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-6xl space-y-6 px-4 sm:px-6 lg:px-8">
        @if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900" role="status">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800" role="alert"><p class="font-bold">The change was not saved.</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_21rem]">
            <div class="space-y-6">
                <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" aria-labelledby="hire-trip-heading"><h2 id="hire-trip-heading" class="text-xl font-black text-emerald-950">Hire plan</h2><dl class="mt-5 grid gap-4 sm:grid-cols-2"><div><dt class="text-xs font-bold uppercase text-slate-500">Pickup</dt><dd class="mt-1 font-semibold">{{ $booking->pickup_at->timezone(config('pisfa.business_timezone'))->format('D, j M Y · H:i') }}</dd><dd class="text-sm text-slate-600">{{ $booking->pickup_location }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Return</dt><dd class="mt-1 font-semibold">{{ $booking->return_at->timezone(config('pisfa.business_timezone'))->format('D, j M Y · H:i') }}</dd><dd class="text-sm text-slate-600">{{ $booking->return_location }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Mode</dt><dd class="mt-1 font-semibold">{{ $booking->hire_mode->label() }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Contact</dt><dd class="mt-1 font-semibold">{{ $booking->contact_phone }}</dd></div></dl>@if($booking->special_requests)<div class="mt-5 rounded-2xl bg-slate-50 p-4"><p class="text-xs font-bold uppercase text-slate-500">Special requests</p><p class="mt-2 whitespace-pre-line text-sm text-slate-700">{{ $booking->special_requests }}</p></div>@endif</section>

        <x-pay-now :payable="$booking" />
                @if($booking->hire_mode === \App\Enums\HireMode::SelfDrive && $booking->selfDriveApplication)<section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" aria-labelledby="self-drive-summary"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 id="self-drive-summary" class="text-xl font-black text-emerald-950">Self-drive verification</h2><p class="mt-1 text-sm text-slate-600">Status: <strong>{{ $booking->selfDriveApplication->status->label() }}</strong></p></div>@can('updateSelfDriveApplication',$booking)<a href="{{ route('portal.car-hire-bookings.self-drive.edit',$booking) }}" class="inline-flex min-h-11 items-center justify-center rounded-xl bg-emerald-700 px-4 text-sm font-bold text-white">Open application</a>@endcan</div>@if($booking->selfDriveApplication->review_reason)<p class="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><strong>Review note:</strong> {{ $booking->selfDriveApplication->review_reason }}</p>@endif</section>@endif
                <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" aria-labelledby="contract-summary"><h2 id="contract-summary" class="text-xl font-black text-emerald-950">Contract</h2>@if($booking->latestNonVoidedContract)<p class="mt-2 text-sm text-slate-600">Version {{ $booking->latestNonVoidedContract->version }} · {{ $booking->latestNonVoidedContract->isAccepted() ? 'Accepted '.$booking->latestNonVoidedContract->accepted_at->timezone(config('pisfa.business_timezone'))->format('j M Y, H:i') : 'Awaiting your review' }}</p><a href="{{ route('portal.car-hire-bookings.contracts.show',[$booking,$booking->latestNonVoidedContract]) }}" class="mt-4 inline-flex min-h-11 items-center rounded-xl border border-emerald-200 px-4 text-sm font-bold text-emerald-800">Review contract</a>@else<p class="mt-2 text-sm text-slate-600">No active contract is currently issued.</p>@endif</section>
                @if($canCancel)<section class="rounded-3xl border border-rose-200 bg-white p-6" aria-labelledby="cancel-hire-heading" x-data="{open:false}"><h2 id="cancel-hire-heading" class="text-lg font-black text-rose-900">Cancel request</h2><p class="mt-2 text-sm text-slate-600">Cancellation is available until {{ $booking->cancellation_cutoff_at->timezone(config('pisfa.business_timezone'))->format('j M Y, H:i') }}.</p><button type="button" @click="open=!open" :aria-expanded="open" class="mt-4 min-h-11 rounded-xl border border-rose-300 px-4 text-sm font-bold text-rose-800">Cancel this hire request</button><form x-show="open" x-cloak method="POST" action="{{ route('portal.car-hire-bookings.cancel',$booking) }}" class="mt-4 space-y-4 rounded-xl bg-rose-50 p-4">@csrf @method('PATCH')<div><label for="hire-cancel-reason" class="block text-sm font-semibold text-rose-900">Reason</label><textarea id="hire-cancel-reason" name="reason" required minlength="5" maxlength="500" rows="3" class="mt-1 block w-full rounded-xl border-rose-300"></textarea></div><label class="flex gap-2 text-sm text-rose-900"><input type="checkbox" name="confirm_cancellation" value="1" required class="mt-1 rounded border-rose-400">I understand this releases the vehicle hold.</label><button class="min-h-11 rounded-xl bg-rose-700 px-4 text-sm font-bold text-white">Confirm cancellation</button></form></section>@endif
            </div>
            <aside class="space-y-5 lg:sticky lg:top-6 lg:self-start"><section class="rounded-3xl bg-emerald-950 p-6 text-white"><h2 class="text-lg font-black">Price snapshot</h2><dl class="mt-5 space-y-3 text-sm"><div class="flex justify-between"><dt class="text-emerald-200">{{ $booking->billable_days }} {{ str('day')->plural($booking->billable_days) }} × daily rate</dt><dd class="font-bold">{{ \App\Support\Money::format((int)$booking->rental_subtotal_minor,$booking->currency) }}</dd></div><div class="flex justify-between"><dt class="text-emerald-200">Security deposit</dt><dd class="font-bold">{{ \App\Support\Money::format((int)$booking->security_deposit_minor,$booking->currency) }}</dd></div><div class="flex justify-between border-t border-emerald-800 pt-3 text-base"><dt class="font-bold">Total</dt><dd class="font-black text-amber-300">{{ \App\Support\Money::format((int)$booking->total_minor,$booking->currency) }}</dd></div></dl><p class="mt-5 rounded-xl bg-white/10 p-3 text-xs leading-5 text-emerald-100"><strong>No payment was taken online.</strong> PISFA will provide verified payment instructions separately after review.</p></section>@if($booking->assignedDriver)<section class="rounded-3xl border border-slate-200 bg-white p-5"><h2 class="font-black text-slate-950">Assigned driver</h2><p class="mt-2 font-semibold">{{ $booking->assignedDriver->name }}</p>@if($booking->assignedDriver->phone)<p class="text-sm text-slate-600">{{ $booking->assignedDriver->phone }}</p>@endif</section>@endif</aside>
        </div>
    </div></div>
</x-app-layout>
