@php
    use App\Enums\CarHireBookingStatus;
    use App\Enums\HireMode;
    use App\Enums\SelfDriveApplicationStatus;
    use App\Enums\VehicleOperationalStatus;
    $timezone=config('pisfa.business_timezone','Africa/Kampala');
    $now=now();
    $application=$booking->selfDriveApplication;
    $contract=$booking->latestNonVoidedContract;
    $contractAccepted=$contract?->isAccepted() ?? false;
    $selfDriveReady=$booking->hire_mode!==HireMode::SelfDrive || $application?->status===SelfDriveApplicationStatus::Approved;
    $rateReady=$booking->hireRate?->is_active && $booking->hireRate->vehicle_id===$booking->vehicle_id && $booking->hireRate->currency===$booking->currency && $booking->hireRate->rateFor($booking->hire_mode)===$booking->daily_rate_minor && $booking->hireRate->security_deposit_minor===$booking->security_deposit_minor;
    $activeAssignment=$booking->driverAssignments->first(fn($assignment)=>$assignment->isActive());
    $driverReady=$booking->hire_mode!==HireMode::WithDriver || ($activeAssignment && $booking->assigned_driver_user_id===$activeAssignment->driver_user_id);
    $canConfirm=$booking->status===CarHireBookingStatus::Pending && $booking->hold_expires_at->isFuture() && $booking->pickup_at->isFuture() && $booking->vehicle->operational_status===VehicleOperationalStatus::Available && $rateReady && $contractAccepted && $selfDriveReady;
    $canStart=$booking->status===CarHireBookingStatus::Confirmed && !$booking->pickup_at->isFuture() && $booking->return_at->isFuture() && $contractAccepted && ($booking->hire_mode===HireMode::SelfDrive ? ($selfDriveReady && $application?->originals_verified_at) : $driverReady);
    $canComplete=$booking->status===CarHireBookingStatus::InProgress && !$booking->return_at->isFuture();
    $canAssign=$booking->hire_mode===HireMode::WithDriver && in_array($booking->status,[CarHireBookingStatus::Confirmed,CarHireBookingStatus::InProgress],true) && $booking->return_at->isFuture();
@endphp
<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><a href="{{route('admin.car-hire-bookings.index')}}" class="text-sm font-bold text-emerald-800 underline">Back to hire bookings</a><div class="mt-4 flex flex-wrap gap-2"><span class="font-mono text-xs font-bold text-emerald-700">{{$booking->reference}}</span><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{{$booking->status->label()}}</span><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-800">{{$booking->hire_mode->label()}}</span></div><h1 class="mt-2 text-2xl font-bold text-slate-950">{{$booking->vehicle_name_snapshot}}</h1><p class="mt-1 text-sm text-slate-500">{{$booking->contact_name}} · {{$booking->contact_phone}}</p></div><a href="{{route('admin.vehicles.show',$booking->vehicle)}}" class="inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-300 px-4 text-sm font-bold text-slate-700">Open vehicle</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">@if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900" role="status">{{session('success')}}</div>@endif @if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800" role="alert"><p class="font-bold">The operation was not completed.</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
        <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_23rem]">
            <div class="space-y-6">
                <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" aria-labelledby="admin-hire-plan"><h2 id="admin-hire-plan" class="text-xl font-black text-emerald-950">Hire plan</h2><dl class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div><dt class="text-xs font-bold uppercase text-slate-500">Pickup</dt><dd class="mt-1 font-semibold">{{$booking->pickup_at->timezone($timezone)->format('D, j M Y H:i')}}</dd><dd class="text-sm text-slate-600">{{$booking->pickup_location}}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Return</dt><dd class="mt-1 font-semibold">{{$booking->return_at->timezone($timezone)->format('D, j M Y H:i')}}</dd><dd class="text-sm text-slate-600">{{$booking->return_location}}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Hold expires</dt><dd class="mt-1 font-semibold">{{$booking->hold_expires_at->timezone($timezone)->format('j M Y H:i')}}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Customer</dt><dd class="mt-1 font-semibold">{{$booking->contact_name}}</dd><dd class="text-sm text-slate-600">{{$booking->contact_email}}<br>{{$booking->contact_phone}}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Registration</dt><dd class="mt-1 font-semibold">{{$booking->registration_plate_snapshot}}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Cancellation cutoff</dt><dd class="mt-1 font-semibold">{{$booking->cancellation_cutoff_at->timezone($timezone)->format('j M Y H:i')}}</dd></div></dl>@if($booking->special_requests)<div class="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><strong>Special requests</strong><p class="mt-1 whitespace-pre-line text-slate-700">{{$booking->special_requests}}</p></div>@endif</section>
                <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" aria-labelledby="admin-price-snapshot"><h2 id="admin-price-snapshot" class="text-xl font-black text-emerald-950">Immutable price snapshot</h2><dl class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-xs uppercase text-slate-500">Daily rate</dt><dd class="mt-1 font-bold">{{\App\Support\Money::format((int)$booking->daily_rate_minor,$booking->currency)}}</dd></div><div><dt class="text-xs uppercase text-slate-500">{{$booking->billable_days}} days</dt><dd class="mt-1 font-bold">{{\App\Support\Money::format((int)$booking->rental_subtotal_minor,$booking->currency)}}</dd></div><div><dt class="text-xs uppercase text-slate-500">Deposit</dt><dd class="mt-1 font-bold">{{\App\Support\Money::format((int)$booking->security_deposit_minor,$booking->currency)}}</dd></div><div><dt class="text-xs uppercase text-slate-500">Total</dt><dd class="mt-1 font-black text-emerald-800">{{\App\Support\Money::format((int)$booking->total_minor,$booking->currency)}}</dd></div></dl><p class="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">This module records no online payment. Use the dedicated verified payment workflow when it becomes available.</p></section>
                <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" aria-labelledby="admin-contract-heading"><h2 id="admin-contract-heading" class="text-xl font-black text-emerald-950">Contract versions</h2>@if($booking->contracts->isEmpty())<p class="mt-3 text-sm text-slate-600">No contract issued.</p>@else<div class="mt-4 space-y-3">@foreach($booking->contracts as $item)<div class="flex flex-col gap-2 rounded-xl bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-mono text-xs font-bold text-emerald-700">{{$item->contract_number}}</p><p class="mt-1 text-sm">Version {{$item->version}} · issued {{$item->issued_at->timezone($timezone)->format('j M Y H:i')}}</p></div><span class="text-sm font-bold {{$item->isVoided()?'text-rose-700':($item->isAccepted()?'text-emerald-700':'text-amber-700')}}">{{$item->isVoided()?'Voided':($item->isAccepted()?'Accepted':'Awaiting acceptance')}}</span></div>@endforeach</div>@endif</section>
                @if($booking->hire_mode===HireMode::SelfDrive && $application)<section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" aria-labelledby="admin-self-drive-heading"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 id="admin-self-drive-heading" class="text-xl font-black text-emerald-950">Self-drive application</h2><p class="mt-1 text-sm text-slate-600">{{$application->status->label()}}</p></div>@if($application->originals_verified_at)<span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">Originals verified</span>@endif</div><dl class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div><dt class="text-xs uppercase text-slate-500">National ID number</dt><dd class="mt-1 break-all font-semibold">{{$application->maskedNationalIdNumber()??'Not provided'}}</dd></div><div><dt class="text-xs uppercase text-slate-500">Driving permit</dt><dd class="mt-1 break-all font-semibold">{{$application->maskedDrivingPermitNumber()??'Not provided'}}</dd></div><div><dt class="text-xs uppercase text-slate-500">Date of birth</dt><dd class="mt-1 font-semibold">{{$application->date_of_birth?->format('j M Y')??'Not provided'}}</dd></div><div><dt class="text-xs uppercase text-slate-500">Issuing country / class</dt><dd class="mt-1 font-semibold">{{$application->driving_permit_issuing_country??'—'}} / {{$application->driving_permit_class??'—'}}</dd></div><div><dt class="text-xs uppercase text-slate-500">Permit validity</dt><dd class="mt-1 font-semibold">{{$application->driving_permit_issued_on?->format('j M Y')??'—'}} to {{$application->driving_permit_expires_on?->format('j M Y')??'—'}}</dd></div></dl>
                    <div class="mt-6"><h3 class="font-bold text-slate-900">Private documents</h3><div class="mt-3 grid gap-3 sm:grid-cols-3">@forelse($booking->documents as $document)<div class="rounded-xl border border-slate-200 p-3"><p class="font-bold">{{$document->document_type->label()}}</p><p class="mt-1 truncate text-xs text-slate-500">{{$document->original_name}} · {{number_format($document->size_bytes/1024)}} KB</p><a href="{{route('admin.car-hire-bookings.documents.download',[$booking,$document])}}" class="mt-3 inline-flex min-h-10 items-center text-xs font-bold text-emerald-800 underline">Authorized download</a></div>@empty<p class="text-sm text-slate-600">No documents uploaded.</p>@endforelse</div></div>
                    @if(in_array($application->status,[SelfDriveApplicationStatus::Submitted],true))<div class="mt-6 grid gap-4 lg:grid-cols-3">@foreach([[SelfDriveApplicationStatus::Approved,'Approve','emerald'],[SelfDriveApplicationStatus::NeedsInformation,'Request information','amber'],[SelfDriveApplicationStatus::Rejected,'Reject','rose']] as [$next,$label,$tone])<form method="POST" action="{{route('admin.car-hire-bookings.self-drive.review',$booking)}}" class="rounded-2xl border border-slate-200 p-4">@csrf @method('PATCH')<input type="hidden" name="status" value="{{$next->value}}"><h3 class="font-bold">{{$label}}</h3><label for="review-reason-{{$next->value}}" class="mt-3 block text-xs font-semibold">Customer-visible reason</label><textarea id="review-reason-{{$next->value}}" name="reason" required minlength="5" maxlength="1000" rows="3" class="mt-1 block w-full rounded-lg border-slate-300"></textarea><label for="review-notes-{{$next->value}}" class="mt-3 block text-xs font-semibold">Internal notes</label><textarea id="review-notes-{{$next->value}}" name="internal_review_notes" maxlength="5000" rows="2" class="mt-1 block w-full rounded-lg border-slate-300"></textarea><button class="mt-3 min-h-10 w-full rounded-lg bg-slate-900 px-3 text-xs font-bold text-white">Record {{$label}}</button></form>@endforeach</div>@endif
                    @if($application->status===SelfDriveApplicationStatus::Approved && !$application->originals_verified_at && $booking->status===CarHireBookingStatus::Confirmed && $booking->return_at->isFuture())<form method="POST" action="{{route('admin.car-hire-bookings.self-drive.verify-originals',$booking)}}" class="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5">@csrf @method('PATCH')<h3 class="font-black text-amber-950">Verify physical originals</h3><p class="mt-2 text-sm text-amber-900">Only complete this after personally comparing the original ID and permit to the uploaded records.</p><label class="mt-4 flex gap-2 text-sm text-amber-950"><input type="checkbox" name="originals_verified" value="1" required class="mt-1 rounded border-amber-400">I personally checked both original documents.</label><label for="verify-originals-phrase" class="mt-4 block text-sm font-semibold text-amber-950">Type VERIFY ORIGINALS</label><input id="verify-originals-phrase" name="confirmation_phrase" required autocomplete="off" class="mt-1 block w-full rounded-xl border-amber-300"><button class="mt-4 min-h-11 rounded-xl bg-amber-700 px-5 text-sm font-bold text-white">Record original verification</button></form>@endif
                </section>@endif
                @if($booking->hire_mode===HireMode::WithDriver)<section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" aria-labelledby="driver-assignment-heading"><h2 id="driver-assignment-heading" class="text-xl font-black text-emerald-950">Driver assignment</h2>@if($canAssign)<form method="POST" action="{{route('admin.car-hire-bookings.assignment',$booking)}}" class="mt-5 grid gap-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end">@csrf @method('PATCH')<div><label for="hire-driver" class="block text-sm font-semibold">Verified active driver</label><select id="hire-driver" name="driver_user_id" class="mt-1 block w-full rounded-xl border-slate-300"><option value="">Release current driver</option>@foreach($drivers as $driver)<option value="{{$driver->id}}" @selected((string)$booking->assigned_driver_user_id===(string)$driver->id)>{{$driver->name}}{{ $driver->phone?' · '.$driver->phone:'' }}</option>@endforeach</select></div><div><label for="driver-change-reason" class="block text-sm font-semibold">Reason <span class="font-normal text-slate-500">(required for release)</span></label><input id="driver-change-reason" name="reason" maxlength="500" class="mt-1 block w-full rounded-xl border-slate-300"></div><button class="min-h-11 rounded-xl bg-slate-900 px-4 text-sm font-bold text-white">Save assignment</button></form>@else<p class="mt-3 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Driver assignment is available only for confirmed or in-progress chauffeur hires before return.</p>@endif @if($booking->driverAssignments->isNotEmpty())<ol class="mt-5 space-y-3">@foreach($booking->driverAssignments as $assignment)<li class="rounded-xl border border-slate-200 p-3 text-sm"><strong>{{$assignment->driver?->name??'Deleted driver'}}</strong><span class="block text-xs text-slate-500">Assigned {{$assignment->assigned_at->timezone($timezone)->format('j M Y H:i')}}{{$assignment->unassigned_at?' · released '.$assignment->unassigned_at->timezone($timezone)->format('j M Y H:i'):' · active'}}</span>@if($assignment->unassignment_reason)<span class="mt-1 block text-xs text-slate-600">Reason: {{$assignment->unassignment_reason}}</span>@endif</li>@endforeach</ol>@endif</section>@endif
            </div>
            <aside class="space-y-6 xl:sticky xl:top-6 xl:self-start"><section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm" aria-labelledby="workflow-heading"><h2 id="workflow-heading" class="font-black text-slate-950">Workflow</h2><div class="mt-4 space-y-3">
                @if($booking->status===CarHireBookingStatus::Pending)
                    @if($canConfirm)<form method="POST" action="{{route('admin.car-hire-bookings.transition',$booking)}}">@csrf @method('PATCH')<input type="hidden" name="status" value="confirmed"><button class="min-h-11 w-full rounded-xl bg-emerald-700 px-4 text-sm font-bold text-white">Confirm booking</button></form>@else<div class="rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-900"><strong>Confirmation blocked.</strong><ul class="mt-2 list-disc pl-4"><li>Hold must be live and pickup future</li><li>Vehicle must be operational</li><li>Current contract must be accepted</li>@if($booking->hire_mode===HireMode::SelfDrive)<li>Self-drive application must be approved</li>@endif</ul></div>@endif
                    @if(!$booking->hold_expires_at->isFuture())<form method="POST" action="{{route('admin.car-hire-bookings.transition',$booking)}}">@csrf @method('PATCH')<input type="hidden" name="status" value="expired"><button class="min-h-11 w-full rounded-xl bg-slate-800 px-4 text-sm font-bold text-white">Mark expired</button></form>@endif
                    @foreach([[CarHireBookingStatus::Declined,'Decline request'],[CarHireBookingStatus::Cancelled,'Cancel request']] as [$next,$label])<details class="rounded-xl border border-rose-200 p-3"><summary class="cursor-pointer text-sm font-bold text-rose-800">{{$label}}</summary><form method="POST" action="{{route('admin.car-hire-bookings.transition',$booking)}}" class="mt-3">@csrf @method('PATCH')<input type="hidden" name="status" value="{{$next->value}}"><label for="transition-reason-{{$next->value}}" class="block text-xs font-semibold">Reason</label><textarea id="transition-reason-{{$next->value}}" name="reason" required minlength="5" maxlength="1000" rows="3" class="mt-1 block w-full rounded-lg border-rose-300"></textarea><button class="mt-3 min-h-10 w-full rounded-lg bg-rose-700 text-xs font-bold text-white">Confirm {{$label}}</button></form></details>@endforeach
                @elseif($booking->status===CarHireBookingStatus::Confirmed)
                    @if($canStart)<form method="POST" action="{{route('admin.car-hire-bookings.transition',$booking)}}">@csrf @method('PATCH')<input type="hidden" name="status" value="in_progress"><button class="min-h-11 w-full rounded-xl bg-sky-700 px-4 text-sm font-bold text-white">Start hire</button></form>@else<p class="rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-900">Start becomes available after pickup and before return, with the accepted current contract and the required original verification or active driver assignment.</p>@endif<details class="rounded-xl border border-rose-200 p-3"><summary class="cursor-pointer text-sm font-bold text-rose-800">Cancel booking</summary><form method="POST" action="{{route('admin.car-hire-bookings.transition',$booking)}}" class="mt-3">@csrf @method('PATCH')<input type="hidden" name="status" value="cancelled"><textarea name="reason" required minlength="5" maxlength="1000" rows="3" aria-label="Cancellation reason" class="block w-full rounded-lg border-rose-300"></textarea><button class="mt-3 min-h-10 w-full rounded-lg bg-rose-700 text-xs font-bold text-white">Confirm cancellation</button></form></details>
                @elseif($booking->status===CarHireBookingStatus::InProgress)
                    @if($canComplete)<form method="POST" action="{{route('admin.car-hire-bookings.transition',$booking)}}">@csrf @method('PATCH')<input type="hidden" name="status" value="completed"><button class="min-h-11 w-full rounded-xl bg-emerald-700 px-4 text-sm font-bold text-white">Complete hire</button></form>@else<p class="rounded-xl bg-sky-50 p-3 text-xs text-sky-900">Completion becomes available at the scheduled return time.</p>@endif
                @else<p class="rounded-xl bg-slate-50 p-3 text-sm text-slate-600">This booking is in a terminal state. No further transitions are available.</p>@endif
            </div></section><section class="rounded-3xl bg-emerald-950 p-5 text-white"><h2 class="font-black">Operational checks</h2><ul class="mt-4 space-y-2 text-sm text-emerald-100"><li>Contract: <strong class="text-white">{{$contractAccepted?'Accepted':'Not accepted'}}</strong></li><li>Vehicle: <strong class="text-white">{{$booking->vehicle->operational_status->label()}}</strong></li>@if($application)<li>Self-drive: <strong class="text-white">{{$application->status->label()}}</strong></li><li>Originals: <strong class="text-white">{{$application->originals_verified_at?'Verified':'Not verified'}}</strong></li>@endif @if($booking->hire_mode===HireMode::WithDriver)<li>Driver: <strong class="text-white">{{$booking->assignedDriver?->name??'Unassigned'}}</strong></li>@endif</ul></section></aside>
        </div>
    </div></div>
</x-app-layout>
