<?php

/**
 * Generates deploy/production.env.template from config/.
 *
 * Written as a generator rather than a hand-maintained file because the old
 * hand-maintained list in docs/HOSTINGER_DEPLOYMENT.md silently fell 71 keys
 * behind as features shipped. A template nobody has to remember to update is
 * the only kind that stays correct.
 *
 * Run from the project root:  php deploy/make-env-template.php
 */

$required = [
    // Nothing works or nothing is safe without these.
    'APP_NAME', 'APP_ENV', 'APP_KEY', 'APP_DEBUG', 'APP_URL', 'APP_TIMEZONE',
    'DB_CONNECTION', 'DB_HOST', 'DB_PORT', 'DB_DATABASE', 'DB_USERNAME', 'DB_PASSWORD',
    'SESSION_SECURE_COOKIE', 'SESSION_ENCRYPT', 'SESSION_DRIVER',
    'MAIL_MAILER', 'MAIL_HOST', 'MAIL_PORT', 'MAIL_USERNAME', 'MAIL_PASSWORD',
    'MAIL_FROM_ADDRESS', 'MAIL_FROM_NAME', 'MAIL_SCHEME',
    // Printed on invoices, quotations and receipts that customers keep.
    'PISFA_COMPANY_NAME', 'PISFA_COMPANY_ADDRESS', 'PISFA_COMPANY_TIN',
    'PISFA_COMPANY_REGISTRATION', 'PISFA_CONTACT_EMAIL', 'PISFA_CONTACT_PHONE',
    'PISFA_BUSINESS_TIMEZONE', 'PISFA_BASE_CURRENCY', 'PISFA_RATE_USD_UGX',
    'PISFA_DEFAULT_CURRENCY', 'PISFA_SUPPORTED_CURRENCIES',
    'LOG_CHANNEL', 'LOG_LEVEL', 'QUEUE_CONNECTION', 'CACHE_STORE', 'FILESYSTEM_DISK',
];

// Framework knobs a shared host never sets. Excluded to keep the template readable.
$skipPrefix = ['AWS_', 'DYNAMODB_', 'BEANSTALKD_', 'SQS_', 'REDIS_', 'MEMCACHED_',
    'PUSHER_', 'ABLY_', 'VITE_', 'POSTGRES_', 'MSSQL_'];

$keys = [];
$seen = [];
foreach (glob('config/*.php') as $file) {
    $src = file_get_contents($file);
    if (! preg_match_all('/env\(\s*[\'"]([A-Z0-9_]+)[\'"]\s*(?:,\s*([^)]*))?\)/', $src, $m, PREG_SET_ORDER)) {
        continue;
    }
    foreach ($m as $hit) {
        $key = $hit[1];
        foreach ($skipPrefix as $prefix) {
            if (str_starts_with($key, $prefix)) { continue 2; }
        }
        $default = isset($hit[2]) ? trim($hit[2]) : '';
        $default = trim($default, "'\" \t");
        if (in_array(strtolower($default), ['null', ''], true)) { $default = ''; }
        if (isset($seen[$key])) { continue; }
        $seen[$key] = true;
        $keys[basename($file, '.php')][$key] = $default;
    }
}
ksort($keys);

$out = [];
$out[] = '# PISFA Tours and Travel — production environment';
$out[] = '#';
$out[] = '# Generated by deploy/make-env-template.php from config/, so it cannot fall';
$out[] = '# behind as features ship. Regenerate after adding a config key.';
$out[] = '#';
$out[] = '# Copy this to .env on the SERVER and fill in every REQUIRED value. Never';
$out[] = '# commit the filled-in file, and never paste real values into a chat, a';
$out[] = '# ticket, or a shell argument.';
$out[] = '#';
$out[] = '# Lines marked REQUIRED must be set. Everything else already has a working';
$out[] = '# default shown after the "=" and can be left alone unless you want to change it.';
$out[] = '';

$requiredCount = 0;
foreach ($keys as $section => $entries) {
    ksort($entries);
    $out[] = '# ' . str_repeat('-', 74);
    $out[] = '# config/' . $section . '.php';
    $out[] = '# ' . str_repeat('-', 74);
    foreach ($entries as $key => $default) {
        if (in_array($key, $required, true)) {
            $out[] = '# REQUIRED';
            $out[] = $key . '=';
            $requiredCount++;
        } else {
            $out[] = $key . '=' . $default;
        }
    }
    $out[] = '';
}

file_put_contents('deploy/production.env.template', implode("\n", $out) . "\n");

printf("Wrote deploy/production.env.template — %d keys, %d marked REQUIRED\n",
    array_sum(array_map('count', $keys)), $requiredCount);
