@extends('layouts.public')

@section('content')
@php $cover = $vehicle->media->firstWhere('is_cover', true) ?? $vehicle->media->first(); @endphp
<div>
    <section class="bg-emerald-950 px-4 py-10 text-white sm:px-6 lg:px-8"><div class="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" class="text-sm text-emerald-100"><a href="{{ route('car-hire.index') }}" class="font-bold hover:text-amber-300">Car hire</a><span class="mx-2" aria-hidden="true">/</span><span aria-current="page">{{ $vehicle->make }} {{ $vehicle->model }}</span></nav><div class="mt-6 grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p class="text-sm font-black uppercase tracking-[0.2em] text-amber-300">{{ str($vehicle->vehicle_type)->replace('_', ' ')->title() }}</p><h1 class="mt-3 text-4xl font-black tracking-tight sm:text-5xl">{{ $vehicle->year }} {{ $vehicle->make }} {{ $vehicle->model }}</h1><p class="mt-5 max-w-2xl text-lg leading-8 text-emerald-100">{{ $vehicle->summary }}</p></div><div class="overflow-hidden rounded-3xl bg-emerald-900 aspect-[16/10]">@if($cover)<img src="{{ $cover->url }}" alt="{{ $cover->alt_text ?: $vehicle->make.' '.$vehicle->model }}" class="h-full w-full object-cover">@else<div class="flex h-full items-center justify-center font-bold text-emerald-100">Image coming soon</div>@endif</div></div></div></section>
    <div class="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[minmax(0,1fr)_22rem] lg:px-8">
        <div class="space-y-8">
            <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" aria-labelledby="specs-heading"><h2 id="specs-heading" class="text-2xl font-black text-emerald-950">Vehicle details</h2><dl class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach ([['Seats',$vehicle->seating_capacity],['Luggage',$vehicle->luggage_capacity.' bags'],['Transmission',str($vehicle->transmission)->replace('_',' ')->title()],['Fuel',str($vehicle->fuel_type)->replace('_',' ')->title()],['Colour',$vehicle->color],['Condition',str($vehicle->condition)->replace('_',' ')->title()]] as [$label,$value])<div class="rounded-2xl bg-slate-50 p-4"><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ $label }}</dt><dd class="mt-1 font-bold text-slate-900">{{ $value }}</dd></div>@endforeach</dl>@if($vehicle->description)<div class="mt-7 whitespace-pre-line text-sm leading-7 text-slate-700">{{ $vehicle->description }}</div>@endif</section>
            @if($vehicle->media->count() > 1)<section aria-labelledby="gallery-heading"><h2 id="gallery-heading" class="text-2xl font-black text-emerald-950">Gallery</h2><div class="mt-5 grid gap-4 sm:grid-cols-2">@foreach($vehicle->media as $medium)<figure class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><img src="{{ $medium->url }}" alt="{{ $medium->alt_text ?: $vehicle->make.' '.$vehicle->model }}" class="aspect-[16/10] w-full object-cover" loading="lazy">@if($medium->caption)<figcaption class="p-3 text-sm text-slate-600">{{ $medium->caption }}</figcaption>@endif</figure>@endforeach</div></section>@endif
        </div>
        <aside class="lg:sticky lg:top-6 lg:self-start"><section class="rounded-3xl border border-emerald-900/10 bg-white p-6 shadow-xl shadow-emerald-950/5" aria-labelledby="rates-heading"><h2 id="rates-heading" class="text-xl font-black text-emerald-950">Daily hire rates</h2><div class="mt-5 space-y-4">@foreach($vehicle->hireRates->groupBy('currency') as $currency => $rates)@php $rate=$rates->first(); @endphp<div class="rounded-2xl bg-emerald-50 p-4"><p class="text-xs font-bold text-emerald-700">{{ $currency }}</p>@if($rate->self_drive_daily_minor)<p class="mt-2 text-sm text-slate-600">Self-drive <strong class="block text-lg text-emerald-950">{{ \App\Support\Money::format((int)$rate->self_drive_daily_minor,$currency) }}/day</strong></p>@endif @if($rate->with_driver_daily_minor)<p class="mt-2 text-sm text-slate-600">With driver <strong class="block text-lg text-emerald-950">{{ \App\Support\Money::format((int)$rate->with_driver_daily_minor,$currency) }}/day</strong></p>@endif @if($rate->security_deposit_minor)<p class="mt-2 text-xs text-slate-600">Refundable security deposit: {{ \App\Support\Money::format((int)$rate->security_deposit_minor,$currency) }}</p>@endif</div>@endforeach</div><p class="mt-5 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-900">Submitting a request does not charge you. The final rate is snapshotted for your selected interval, then reviewed by PISFA.</p><a href="{{ route('car-hire-bookings.create', ['vehicle'=>$vehicle] + request()->only(['pickup_at','return_at','hire_mode','currency'])) }}" class="mt-5 inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-emerald-800 px-5 py-3 text-sm font-bold text-white hover:bg-emerald-900">Request this vehicle</a></section></aside>
    </div>
</div>
@endsection
