<?php

namespace App\Actions\Documents;

use App\Enums\DocumentCategory;
use App\Models\Document;
use App\Models\User;
use App\Services\AuditLogger;
use App\Services\Documents\DocumentStorage;
use App\Services\Documents\FileInspector;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Throwable;

class StoreDocument
{
    public function __construct(
        private readonly FileInspector $inspector,
        private readonly DocumentStorage $storage,
        private readonly AuditLogger $auditLogger,
    ) {}

    /**
     * @param  array<string, mixed>  $metadata
     */
    public function execute(
        User $actor,
        Model $owner,
        DocumentCategory $category,
        UploadedFile $file,
        array $metadata = [],
        int $sortOrder = 0,
    ): Document {
        if ($category->isGenerated()) {
            throw ValidationException::withMessages([
                'file' => $category->label().' is generated by PISFA and cannot be uploaded.',
            ]);
        }

        // Inspect before writing anything. A rejected file never reaches disk.
        $inspection = $this->inspector->inspect($file, $category);
        $visibility = $category->visibility();

        $written = $this->storage->putUpload(
            $file,
            $visibility,
            $this->directoryFor($owner, $category),
            $inspection['extension'],
        );

        try {
            return DB::transaction(function () use (
                $actor,
                $owner,
                $category,
                $file,
                $metadata,
                $sortOrder,
                $inspection,
                $visibility,
                $written,
            ): Document {
                $lockedActor = User::query()->whereKey($actor->getKey())->lockForUpdate()->firstOrFail();

                $previous = Document::query()
                    ->where('documentable_type', $owner->getMorphClass())
                    ->where('documentable_id', $owner->getKey())
                    ->ofCategory($category)
                    ->current()
                    ->lockForUpdate()
                    ->get();

                $highestVersion = (int) Document::query()
                    ->where('documentable_type', $owner->getMorphClass())
                    ->where('documentable_id', $owner->getKey())
                    ->ofCategory($category)
                    ->withTrashed()
                    ->max('version');

                // A versioned category supersedes its predecessor and keeps it.
                // A single-slot category replaces its predecessor outright.
                $supersededFiles = [];

                foreach ($previous as $document) {
                    if ($category->isVersioned()) {
                        $document->forceFill(['is_current' => false])->save();

                        continue;
                    }

                    $supersededFiles[] = ['disk' => $document->disk, 'path' => $document->path];
                    $document->forceFill(['is_current' => false])->save();
                    $document->delete();
                }

                $created = new Document;
                $created->forceFill([
                    'documentable_type' => $owner->getMorphClass(),
                    'documentable_id' => $owner->getKey(),
                    'category' => $category,
                    'visibility' => $visibility,
                    'disk' => $written['disk'],
                    'path' => $written['path'],
                    'original_name' => mb_substr(basename($file->getClientOriginalName()), 0, 255),
                    'mime_type' => $inspection['mime'],
                    'size_bytes' => $inspection['size'],
                    'content_sha256' => $inspection['checksum'],
                    'image_width' => $inspection['width'],
                    'image_height' => $inspection['height'],
                    'version' => $highestVersion + 1,
                    'is_current' => true,
                    'sort_order' => $sortOrder,
                    'uploaded_by_user_id' => $lockedActor->getKey(),
                    'is_generated' => false,
                    'metadata' => $metadata === [] ? null : $metadata,
                ])->save();

                $this->auditLogger->record(
                    event: 'document.uploaded',
                    auditable: $created,
                    newValues: [
                        'documentable_type' => $created->documentable_type,
                        'documentable_id' => $created->documentable_id,
                        'category' => $category->value,
                        'visibility' => $visibility->value,
                        'mime_type' => $created->mime_type,
                        'size_bytes' => $created->size_bytes,
                        'version' => $created->version,
                        'superseded' => $previous->count(),
                    ],
                    user: $lockedActor,
                );

                // Only purge replaced files once the transaction commits, so a
                // rollback cannot leave a database row pointing at a gone file.
                DB::afterCommit(function () use ($supersededFiles): void {
                    foreach ($supersededFiles as $file) {
                        $this->storage->delete($file['disk'], $file['path']);
                    }
                });

                return $created;
            }, 3);
        } catch (Throwable $exception) {
            // The row never committed, so the orphaned file must go.
            $this->storage->delete($written['disk'], $written['path']);

            throw $exception;
        }
    }

    private function directoryFor(Model $owner, DocumentCategory $category): string
    {
        $ownerSegment = str(class_basename($owner))->snake()->plural()->toString();

        return $ownerSegment.'/'.$owner->getKey().'/'.$category->value;
    }
}
