/*
 * PISFA Tours and Travel — service worker.
 *
 * Generated by App\Http\Controllers\Pwa\ProgressiveWebAppController so the cache
 * version tracks the built assets. Do not edit a cached copy; edit the Blade
 * template it comes from.
 *
 * THE RULE THIS FILE EXISTS TO ENFORCE: HTML is never cached.
 *
 * Almost every PWA tutorial caches pages for offline reading. Doing that here
 * would be a data leak. A customer's portal page contains their bookings, their
 * name, and their invoices; a staff console page contains other people's. Phones
 * and desktops are shared — a family device, a shared office machine, an
 * internet cafe — and a cached HTML response is served to whoever asks next,
 * signed in or not, until the cache is cleared. Logging out would not remove it.
 *
 * So: content-hashed static assets are cached, because their URL changes when
 * their content does and they contain nobody's data. Everything else goes to
 * the network, and if the network is not there the visitor gets the offline
 * page rather than somebody else's booking.
 */

const VERSION = @json($version);
const STATIC_CACHE = `pisfa-static-${VERSION}`;
const OFFLINE_URL = @json($offlineUrl);
const PRECACHE = @json($precache);

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(STATIC_CACHE)
            .then((cache) => cache.addAll(PRECACHE))
            // One missing asset must not prevent the worker installing at all;
            // a worker that fails to install leaves the visitor with no offline
            // page whatsoever.
            .catch(() => undefined)
            .then(() => self.skipWaiting()),
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys()
            .then((keys) => Promise.all(
                keys
                    .filter((key) => key.startsWith('pisfa-') && key !== STATIC_CACHE)
                    .map((key) => caches.delete(key)),
            ))
            .then(() => self.clients.claim()),
    );
});

self.addEventListener('fetch', (event) => {
    const request = event.request;

    // Only GET. A POST is a booking, a payment, or a message — replaying one
    // from a cache would submit it twice.
    if (request.method !== 'GET') {
        return;
    }

    const url = new URL(request.url);

    // Never touch another origin, and never touch a request carrying
    // credentials we would then be responsible for.
    if (url.origin !== self.location.origin) {
        return;
    }

    // Never intercept the things that must always be live: the webhook
    // endpoints, the chat poll, the health check, and anything under /admin.
    if (
        url.pathname.startsWith('/webhooks/')
        || url.pathname.startsWith('/chat/')
        || url.pathname.startsWith('/admin/')
        || url.pathname === '/health'
        || url.pathname === '/up'
    ) {
        return;
    }

    // Content-hashed build output: the URL changes when the file does, so a
    // cache hit is always correct and always safe. This is the only thing this
    // worker serves from a cache.
    if (url.pathname.startsWith('/build/') || url.pathname.startsWith('/icons/')) {
        event.respondWith(cacheFirst(request));

        return;
    }

    // Everything else — every page, every API response — is network-only, with
    // the offline page as the fallback for a navigation. Nothing is stored.
    if (request.mode === 'navigate') {
        event.respondWith(networkThenOfflinePage(request));
    }
});

async function cacheFirst(request) {
    const cached = await caches.match(request);

    if (cached) {
        return cached;
    }

    const response = await fetch(request);

    // Only a complete, successful, same-origin response is worth keeping. An
    // opaque or partial response cached here would be served forever.
    if (response.ok && response.type === 'basic') {
        const cache = await caches.open(STATIC_CACHE);
        cache.put(request, response.clone());
    }

    return response;
}

async function networkThenOfflinePage(request) {
    try {
        return await fetch(request);
    } catch (error) {
        const offline = await caches.match(OFFLINE_URL);

        return offline ?? new Response(
            '<!doctype html><meta charset="utf-8"><title>Offline</title>'
            + '<p style="font-family:system-ui;padding:2rem">You are offline. '
            + 'Reconnect and try again.</p>',
            { status: 503, headers: { 'Content-Type': 'text/html; charset=utf-8' } },
        );
    }
}
