<?php

namespace App\Enums;

enum DocumentCategory: string
{
    // Uploaded by people
    case IdentityDocument = 'identity_document';
    case DrivingPermit = 'driving_permit';
    case ApplicantPhoto = 'applicant_photo';
    case ImportDocument = 'import_document';
    case InsuranceDocument = 'insurance_document';
    case VehicleRegistration = 'vehicle_registration';
    case ExpenseReceipt = 'expense_receipt';
    case TourMedia = 'tour_media';
    case VehicleMedia = 'vehicle_media';
    case PropertyMedia = 'property_media';
    case BlogMedia = 'blog_media';
    case ReviewMedia = 'review_media';
    case TeamPhoto = 'team_photo';
    case ServiceIcon = 'service_icon';
    case DriverPhoto = 'driver_photo';
    case GalleryImage = 'gallery_image';

    // Generated by the system
    case RentalContract = 'rental_contract';
    case LeaseContract = 'lease_contract';
    case Quotation = 'quotation';
    case Invoice = 'invoice';
    case Payslip = 'payslip';
    case PaymentReceipt = 'payment_receipt';
    case Statement = 'statement';

    public function label(): string
    {
        return match ($this) {
            self::IdentityDocument => 'Identity document',
            self::DrivingPermit => 'Driving permit',
            self::ApplicantPhoto => 'Applicant photograph',
            self::ImportDocument => 'Import document',
            self::InsuranceDocument => 'Insurance document',
            self::VehicleRegistration => 'Vehicle registration',
            self::ExpenseReceipt => 'Expense receipt',
            self::TourMedia => 'Tour photograph',
            self::VehicleMedia => 'Vehicle photograph',
            self::PropertyMedia => 'Property photograph',
            self::BlogMedia => 'Blog image',
            self::ReviewMedia => 'Review photograph',
            self::TeamPhoto => 'Team photograph',
            self::ServiceIcon => 'Service image',
            self::DriverPhoto => 'Driver photograph',
            self::GalleryImage => 'Gallery photograph',
            self::RentalContract => 'Rental contract',
            self::LeaseContract => 'Lease contract',
            self::Quotation => 'Quotation',
            self::Invoice => 'Invoice',
            self::Payslip => 'Payslip',
            self::PaymentReceipt => 'Payment receipt',
            self::Statement => 'Statement',
        };
    }

    /**
     * Categories holding personal, financial, or contractual data always land
     * on the private disk regardless of what a caller asks for.
     */
    public function visibility(): DocumentVisibility
    {
        return match ($this) {
            self::TourMedia, self::VehicleMedia, self::PropertyMedia,
            self::BlogMedia, self::ReviewMedia,
            self::TeamPhoto, self::ServiceIcon, self::GalleryImage => DocumentVisibility::Public,

            /*
             * DriverPhoto is deliberately not in that list.
             *
             * A team photograph is marketing: the person chose to appear on the
             * About page. A driver's photograph exists so one customer, at one
             * airport, on one morning, can be certain the man walking towards
             * them is the man PISFA sent. That is a good reason to show it to
             * that customer and no reason at all to put a staff member's face
             * on a public disk where the URL outlives the trip.
             *
             * It is served through short-lived signed links minted only for a
             * viewer who already holds the booking.
             */
            default => DocumentVisibility::Private,
        };
    }

    /**
     * System-generated documents are produced by a renderer, never accepted
     * from an upload form.
     */
    public function isGenerated(): bool
    {
        return in_array($this, [
            self::RentalContract,
            self::LeaseContract,
            self::Quotation,
            self::Invoice,
            self::Payslip,
            self::PaymentReceipt,
            self::Statement,
        ], true);
    }

    /**
     * Categories that must be an image, so dimension rules apply.
     */
    public function requiresImage(): bool
    {
        return in_array($this, [
            self::ApplicantPhoto,
            self::VehicleMedia,
            self::PropertyMedia,
            self::BlogMedia,
            self::ReviewMedia,
            self::TeamPhoto,
            self::ServiceIcon,
            self::DriverPhoto,
            self::GalleryImage,
        ], true);
    }

    /**
     * Whether a record may hold many of these at once.
     *
     * Photographs are a gallery: a listing has a front, a rear and an interior
     * shot, and uploading the second must not remove the first. Every other
     * category is a single slot or a version chain, where a new file genuinely
     * does supersede its predecessor.
     *
     * Without this distinction media fell into the single-slot branch, so each
     * upload deleted the one before it and a listing could never show more than
     * one picture.
     */
    public function isCollection(): bool
    {
        return in_array($this, [
            self::TourMedia,
            self::VehicleMedia,
            self::PropertyMedia,
            self::BlogMedia,
            self::ReviewMedia,
            self::TeamPhoto,
            self::ServiceIcon,
            self::GalleryImage,
        ], true);
    }

    /**
     * Versioned categories keep prior revisions instead of overwriting, because
     * the superseded document may still be referenced by an agreement.
     */
    public function isVersioned(): bool
    {
        return in_array($this, [
            self::RentalContract,
            self::LeaseContract,
            self::Quotation,
            self::Invoice,
            self::Statement,
            self::InsuranceDocument,
            self::VehicleRegistration,
        ], true);
    }

    /** @return list<self> */
    public static function uploadableCases(): array
    {
        return array_values(array_filter(
            self::cases(),
            static fn (self $case): bool => ! $case->isGenerated(),
        ));
    }
}
